kind: pipeline
name: default

steps:
- name: run
  image: rust
  # volumes:
  # - name: vendor
  #   path: /drone/src/vendor/
  commands:
  # - cargo vendor
  - cargo build --release
  - cargo run --release
  - ls target/release
- name: deploy
  image: appleboy/drone-scp
  settings:
    host: sh.thepog.cn
    username: root
    password: 330681Ycx
    target: /root/
    source: /drone/src/release
# volumes:
#   - name: vendor
#     host:
#       path: /root/vendor/