kind: pipeline
name: default

steps:
- name: run
  image: rust
  # volumes:
  # - name: vendor
  #   path: /drone/src/vendor/
  commands:
  # - cargo vendor
  - cargo build
  - cargo run

# volumes:
#   - name: vendor
#     host:
#       path: /root/vendor/