kind: pipeline
name: default

steps:
- name: run
  image: rust
  # volumes:
  # - name: vendor
  #   path: /drone/src/vendor/
  commands:
  # - cargo vendor
  - cargo build --release
  - cargo run --release
  - ls target/release
# - name: deploy
#   image: appleboy/drone-scp
#   settings:
#     host: sh.thepog.cn
#     username: root
#     password:
#       from_secret: ssh_password
#     target: /root/hello
#     source: /drone/src/target/release/hello-ex
#     rm: true
- name: build-image
  image: plugins/docker
  settings:
    repo: hello
    dockerfile: /drone/src/Dockerfile
# volumes:
#   - name: vendor
#     host:
#       path: /root/vendor/ 
##